### ISSUE TITLE
Exclude additional xml parameters

### ISSUE THREAD

**Issue by yahorm** [Mateusz512/IntelliJ-CRX-cleaner#1]
What? 
There are two more parameters to exclude from xml.
Example:
`cq:lastRolledout="{Date}2020-01-01T12:12:12.121Z"`
`cq:lastRolledoutBy="admin"`

How to fix?
Additional line could be added into the `ConfigurationProvider`
`"""cq:lastRolledout.*""".toRegex()`

**Comment by Mateusz512** [comment]
YOLO, commited to master 🕺
