### ISSUE TITLE
Support for Intellij 2021.1

### ISSUE THREAD

**Issue by tauba** [Mateusz512/IntelliJ-CRX-cleaner#2]
Hello

Today I updated my Intellij and lost support for the plugin.

Here is the build version
![image](https://user-images.githubusercontent.com/2256574/114100039-1b93f900-989a-11eb-8e76-6c5a6a2ddee7.png)

Any plans to some update?
:)

**Comment by Mateusz512** [comment]
@tauba the release is pending approval, it should be available within a few days
