### ISSUE TITLE
Not longer working on IntelliJ IDEA 2021.2

### ISSUE THREAD

**Issue by wimsymons** [Mateusz512/IntelliJ-CRX-cleaner#4]
Hi there,

The plugin is broken on IntelliJ 2012.2 as that version isn't supported in the manifest.

You see a message "Incompatible: requires IDE build 211.* or older" in the plugins dialog.

This is on version 0.0.3.

Can you fix this please?

Kind regards

Wim

**Comment by tauba** [comment]
Same here
![image](https://user-images.githubusercontent.com/2256574/138927930-f4216014-a079-4f07-8d94-a800e7e58c9a.png)

**Comment by Mateusz512** [comment]
[Released](https://github.com/Mateusz512/IntelliJ-CRX-cleaner/releases/tag/v0.0.4). Should be available for download on JB Marketplace soon 🤞

**Comment by tauba** [comment]
Thanks :D

**Comment by wimsymons** [comment]
Thank you! 🥇
